sonar.projectKey=Raj-SW_petstore-backend
sonar.organization=raj-sw
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/tmp/**,**/coverage/**,**/scripts/**,**/*.test.js,tests/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
